### ISSUE TITLE
Catching a publish error ("Not authorized" is undetected)

### ISSUE THREAD

**Issue by NorbNorb** [colinl/node-red-guaranteed-delivery#5]
Hi,

I have noticed that it is not recognized if the client lacks the permissions to publish on a certain topic. An error is displayed in the debug window, but it remains unhandled.

The following scenario was given: my Node-RED client sends a message on `data/temperature` to the MQTT server. As a test, I removed the authorization for publishing on `data/temperature` attached to the client certificate on the server.

In Node-RED, the following error from the 'MQTT Out' node is then displayed in the debug window:

**Error: Publish error: Not authorized**

The attached error stack is:
```
Error: Publish error: Not authorized
    at MqttClient._handleAck (/usr/lib/node_modules/node-red/node_modules/@node-red/nodes/node_modules/mqtt/lib/client.js:1612:15)
    at MqttClient._handlePacket (/usr/lib/node_modules/node-red/node_modules/@node-red/nodes/node_modules/mqtt/lib/client.js:542:12)
    at work (/usr/lib/node_modules/node-red/node_modules/@node-red/nodes/node_modules/mqtt/lib/client.js:438:12)
    at writable._write (/usr/lib/node_modules/node-red/node_modules/@node-red/nodes/node_modules/mqtt/lib/client.js:452:5)
    at doWrite (/usr/lib/node_modules/node-red/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/usr/lib/node_modules/node-red/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Writable.write (/usr/lib/node_modules/node-red/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at TLSSocket.ondata (node:internal/streams/readable:809:22)
    at TLSSocket.emit (node:events:517:28)
    at addChunk (no...
```

The problem I see is that the publishing failed but the "MQTT complete" node also sends out a message, resulting in the mechanism to 'think' everything's okay and there's no need to keep the message cached.

![1](https://github.com/user-attachments/assets/2befddc2-ac29-457e-b0c6-3fef48fc119a)
![2](https://github.com/user-attachments/assets/55770a89-5c71-4fa9-9111-c24c1a6272c5)

<details>
  <summary>Node-RED Nodes</summary>
Here's the flow for easier reproduction of the issue. You have to add your own MQTT server configuration.

```
 [
     {
         "id": "8ca680d0cbf7e3c6",
         "type": "link out",
         "z": "d6d0e41b7de02a4b",
         "name": "Redeliver MQTT message (Link Out)",
         "mode": "link",
         "links": [
             "9ea064625b8edf3b"
         ],
         "x": 1245,
         "y": 320,
         "wires": []
     },
     {
         "id": "9ea064625b8edf3b",
         "type": "link in",
         "z": "d6d0e41b7de02a4b",
         "name": "Redeliver MQTT message (Link In)",
         "links": [
             "8ca680d0cbf7e3c6"
         ],
         "x": 285,
         "y": 240,
         "wires": [
             [
                 "dadb3603d900311e"
             ]
         ]
     },
     {
         "id": "cbf60be7e4942d14",
         "type": "comment",
         "z": "d6d0e41b7de02a4b",
         "name": "Send MQTT messages to this link",
         "info": "",
         "x": 270,
         "y": 160,
         "wires": []
     },
     {
         "id": "9383bf60fd86f412",
         "type": "complete",
         "z": "d6d0e41b7de02a4b",
         "name": "MQTT Complete",
         "scope": [
             "de277d8fedaeeeea"
         ],
         "uncaught": false,
         "x": 220,
         "y": 340,
         "wires": [
             [
                 "b45fe143cb9750cc",
                 "7853349c62884a87"
             ]
         ]
     },
     {
         "id": "3d934b40b7653e9b",
         "type": "join",
         "z": "d6d0e41b7de02a4b",
         "name": "Join with key",
         "mode": "custom",
         "build": "object",
         "property": "payload",
         "propertyType": "msg",
         "key": "key",
         "joiner": "\\n",
         "joinerType": "str",
         "accumulate": true,
         "timeout": "",
         "count": "1",
         "reduceRight": false,
         "reduceExp": "",
         "reduceInit": "",
         "reduceInitType": "",
         "reduceFixup": "",
         "x": 780,
         "y": 320,
         "wires": [
             [
                 "e255482d73d1d7e1"
             ]
         ]
     },
     {
         "id": "b45fe143cb9750cc",
         "type": "change",
         "z": "d6d0e41b7de02a4b",
         "name": "key: completed, save topic and payload",
         "rules": [
             {
                 "t": "set",
                 "p": "key",
                 "pt": "msg",
                 "to": "completed",
                 "tot": "str"
             },
             {
                 "t": "move",
                 "p": "payload",
                 "pt": "msg",
                 "to": "payload.data",
                 "tot": "msg"
             },
             {
                 "t": "set",
                 "p": "payload.topic",
                 "pt": "msg",
                 "to": "topic",
                 "tot": "msg"
             }
         ],
         "action": "",
         "property": "",
         "from": "",
         "to": "",
         "reg": false,
         "x": 500,
         "y": 340,
         "wires": [
             [
                 "3d934b40b7653e9b"
             ]
         ]
     },
     {
         "id": "ee87428e6c11d64e",
         "type": "change",
         "z": "d6d0e41b7de02a4b",
         "name": "key: sending, save topic and payload",
         "rules": [
             {
                 "t": "set",
                 "p": "key",
                 "pt": "msg",
                 "to": "sending",
                 "tot": "str"
             },
             {
                 "t": "move",
                 "p": "payload",
                 "pt": "msg",
                 "to": "payload.data",
                 "tot": "msg"
             },
             {
                 "t": "set",
                 "p": "payload.topic",
                 "pt": "msg",
                 "to": "topic",
                 "tot": "msg"
             }
         ],
         "action": "",
         "property": "",
         "from": "",
         "to": "",
         "reg": false,
         "x": 490,
         "y": 300,
         "wires": [
             [
                 "3d934b40b7653e9b"
             ]
         ]
     },
     {
         "id": "e255482d73d1d7e1",
         "type": "function",
         "z": "d6d0e41b7de02a4b",
         "name": "Check if messages match - OK or FAIL",
         "func": "/** Check that the message that is has been sent (completed) is the one that has just been passed to the MQTT node (sending)\n * payload.sending contains last msg sent to MQTT node\n * payload.completed contains msg indicated completed by MQTT node\n * in each case the payload contains topic of message and payload value in data\n */ \nconst previousKey = context.get(\"previousKey\") || \"\"\nconst thisKey = msg.key\n\n//node.warn(typeof msg.payload.sending.data)\nif (thisKey === \"completed\"  &&  previousKey === \"sending\") {\n    let equal = false           // whether messages are equivalent\n    // topics must be the same\n    if (msg.payload.sending.topic === msg.payload.completed.topic) {\n        if (typeof msg.payload.sending.data === \"string\") {\n            equal = compareDirect(msg.payload.sending.data, msg.payload.completed.data)\n        } else if (Buffer.isBuffer(msg.payload.sending.data)) {\n            equal = compareBuffers(msg.payload.sending.data, msg.payload.completed.data)\n        } else {\n            equal = compareJSON(msg.payload.sending.data, msg.payload.completed.data)\n        }\n    }\n    if (equal) {\n        msg.control = \"OK\"\n    } else {\n        msg.control = \"FAIL\"\n    }\n} else {\n    // out of sequence so ignore\n    msg = null\n}\ncontext.set(\"previousKey\", thisKey)\nreturn msg;\n\nfunction compareJSON(sending, completed) {\n    // compares JSON version of payload sent with that from the Complete node\n    return completed === JSON.stringify(sending)\n}\n\nfunction compareDirect(sending, completed) {\n    // directly compares payload sent with that from the Complete node\n    return completed === sending \n}\n\nfunction compareBuffers(sending, completed) {\n    // compares buffer payload sent with that from the Complete node\n    let answer = false\n    // check completed is also a buffer\n    if (Buffer.isBuffer(completed)) {\n        answer = Buffer.compare(sending, completed) === 0\n    }\n    return answer \n}",
         "outputs": 1,
         "timeout": 0,
         "noerr": 0,
         "initialize": "",
         "finalize": "",
         "libs": [],
         "x": 1050,
         "y": 320,
         "wires": [
             [
                 "8ca680d0cbf7e3c6"
             ]
         ],
         "info": "// nrlint function-eslint:off\n"
     },
     {
         "id": "3489610635bc3803",
         "type": "link in",
         "z": "d6d0e41b7de02a4b",
         "name": "Send to MQTT",
         "links": [],
         "x": 220,
         "y": 200,
         "wires": [
             [
                 "dadb3603d900311e"
             ]
         ],
         "l": true
     },
     {
         "id": "90f4e2c9a82aec78",
         "type": "guaranteed-delivery",
         "z": "d6d0e41b7de02a4b",
         "name": "",
         "controlProperty": "control",
         "OKValue": "OK",
         "FAILValue": "FAIL",
         "retrySecs": 60,
         "timeout": 5,
         "maxQueue": 525600,
         "contextStore": "file",
         "x": 500,
         "y": 200,
         "wires": [
             [
                 "a20490b7f75f79f7",
                 "de277d8fedaeeeea",
                 "bd3df78edf93087f"
             ]
         ]
     },
     {
         "id": "de277d8fedaeeeea",
         "type": "mqtt out",
         "z": "d6d0e41b7de02a4b",
         "name": "Publish on AWS MQTT Broker",
         "topic": "",
         "qos": "1",
         "retain": "",
         "respTopic": "",
         "contentType": "",
         "userProps": "",
         "correl": "",
         "expiry": "",
         "broker": "e65ad34c07f6fe61",
         "x": 860,
         "y": 200,
         "wires": []
     },
     {
         "id": "bd3df78edf93087f",
         "type": "debug",
         "z": "d6d0e41b7de02a4b",
         "name": "Message to MQTT broker",
         "active": false,
         "tosidebar": true,
         "console": false,
         "tostatus": false,
         "complete": "payload",
         "targetType": "msg",
         "statusVal": "",
         "statusType": "auto",
         "x": 800,
         "y": 160,
         "wires": []
     },
     {
         "id": "7853349c62884a87",
         "type": "debug",
         "z": "d6d0e41b7de02a4b",
         "name": "MQTT Complete Output",
         "active": true,
         "tosidebar": true,
         "console": false,
         "tostatus": false,
         "complete": "payload",
         "targetType": "msg",
         "statusVal": "",
         "statusType": "auto",
         "x": 440,
         "y": 380,
         "wires": []
     },
     {
         "id": "1eb7eea471339c08",
         "type": "catch",
         "z": "d6d0e41b7de02a4b",
         "name": "MQTT Failed",
         "scope": [
             "de277d8fedaeeeea"
         ],
         "uncaught": false,
         "x": 220,
         "y": 440,
         "wires": [
             [
                 "94e97bd5509eb81f"
             ]
         ]
     },
     {
         "id": "94e97bd5509eb81f",
         "type": "debug",
         "z": "d6d0e41b7de02a4b",
         "name": "MQTT Catch Output",
         "active": true,
         "tosidebar": true,
         "console": false,
         "tostatus": false,
         "complete": "true",
         "targetType": "full",
         "statusVal": "",
         "statusType": "auto",
         "x": 430,
         "y": 440,
         "wires": []
     },
     {
         "id": "dadb3603d900311e",
         "type": "junction",
         "z": "d6d0e41b7de02a4b",
         "x": 340,
         "y": 200,
         "wires": [
             [
                 "90f4e2c9a82aec78"
             ]
         ]
     },
     {
         "id": "a20490b7f75f79f7",
         "type": "junction",
         "z": "d6d0e41b7de02a4b",
         "x": 660,
         "y": 200,
         "wires": [
             [
                 "ee87428e6c11d64e"
             ]
         ]
     }
 ]
```
</details>

**Comment by colinl** [comment]
Are you using the latest version of node red? 

If you add a Catch node, does it catch the error?

**Comment by NorbNorb** [comment]
It's 3.1.10.
The red Catch Node catches the error, yes. But the complete node as well. Both produce output. In my example from the screenshot above, both the green and red node produce output when the message can't be published.

**Comment by colinl** [comment]
Can you check it with the latest node red please? The mqtt node may have been fixed. It should not produce both complete and error.

**Comment by NorbNorb** [comment]
I just tested it on a different machine with v4.0.2 installed. No problem over there with the newer version of Node-RED. The catch node produces an output, the complete node not.
I can't upgrade right now on my main device, but good to know that this issue can be solved just by upgrading Node-RED.
Thank you for your fast support!
